; Simple SNES Mode 3 demo using pre-baked BG1 tiles, tilemap, and palette
    ; Generated by ChatGPT - untested, but should be a reasonable starting point.
    ;
    ; Assembler: WLA-DX (wla-65816 + wlalink)
    ;
    ; Builds a LoROM, 2 banks (128KB). Code in bank 0, data in bank 1.
    ;
    ; This demo:
    ;   - Forces blank
    ;   - Sets Mode 3, BG1 char/screen bases
    ;   - DMA-loads CGRAM palette from ROM
    ;   - DMA-loads BG1 tilemap and tile data from ROM to VRAM
    ;   - Then turns display on and loops forever.
    ;
    ; You can extend it with NMI + per-frame DMA to animate.

    .MEMORYMAP
      DEFAULTSLOT 0
      SLOTSIZE $8000
      SLOT 0 $8000
    .ENDME

    .ROMBANKSIZE $8000
    .ROMBANKS 2

    ; ----------------------------------------------------------
    ; Bank 0 - code + vectors + internal header
    ; ----------------------------------------------------------

    .BANK 0 SLOT 0
    .ORG $8000

Start:
    SEI                 ; disable IRQs
    CLC
    XCE                 ; stay in emulation (just in case)

    ; Init stack (emulation mode uses page 1)
    LDX #$FF
    TXS

    ; Force blank, screen off
    LDA #$80
    STA $2100           ; INIDISP: bit7=1 (forced blank)

    ; Basic PPU setup
    LDA #$00
    STA $2101           ; OBSEL (sprites) - default
    STA $2102           ; OAMADDL
    STA $2103           ; OAMADDH

    ; Mode 3, BG1 on
    LDA #$03
    STA $2105           ; BGMODE = 3

    ; BG1SC - screen base, 32x32
    ; Screen base at VRAM $1000 -> $1000 / $800 = 2
    LDA #$02
    STA $2107           ; BG1SC

    ; BG12NBA - BG1 char base
    ; Char base at VRAM $0000 -> value 0
    LDA #$00
    STA $210B           ; BG12NBA

    ; BG1 scroll = 0,0
    STZ $210D
    STZ $210D
    STZ $210E
    STZ $210E

    ; ------------------------------------------------------
    ; Load palette to CGRAM via DMA (channel 0)
    ; ------------------------------------------------------

    ; CGRAM address = 0
    STZ $2121

    ; DMA from ROM (bank 1) at label PaletteData
    LDA #$02            ; mode 2: write to 1 reg, dest fixed
    STA $4300           ; DMAP0
    LDA #$22            ; dest: $2122 (CGRAM data)
    STA $4301           ; BBAD0

    LDA #<PaletteData
    STA $4302           ; A1T0L
    LDA #>PaletteData
    STA $4303           ; A1T0H
    LDA #^PaletteData
    STA $4304           ; A1B0

    ; Transfer 512 bytes (256 colors)
    LDA #$00
    STA $4307           ; DAS0H (high size)
    LDA #<512
    STA $4305           ; DAS0L
    LDA #>512
    STA $4306           ; DAS0M

    LDA #$01
    STA $420B           ; MDMAEN - start DMA ch0

    ; ------------------------------------------------------
    ; Load tilemap into VRAM $1000 via DMA (channel 1)
    ; ------------------------------------------------------

    ; VRAM increment after high byte write, word address
    LDA #$80
    STA $2115           ; VMAIN

    ; Set VRAM address = $1000 -> $1000 / 2 = $0800 (word address)
    LDA #$00
    STA $2116           ; VMADDL
    LDA #$08
    STA $2117           ; VMADDH

    ; DMA channel 1: mode 1 (2 regs, write to $2118/9)
    LDA #$01
    STA $4310           ; DMAP1
    LDA #$18            ; dest $2118
    STA $4311           ; BBAD1

    LDA #<TilemapData
    STA $4312           ; A1T1L
    LDA #>TilemapData
    STA $4313           ; A1T1H
    LDA #^TilemapData
    STA $4314           ; A1B1

    ; Size: 2048 bytes
    LDA #$00
    STA $4317           ; DAS1H
    LDA #<2048
    STA $4315           ; DAS1L
    LDA #>2048
    STA $4316           ; DAS1M

    LDA #$02
    STA $420B           ; MDMAEN - start DMA ch1

    ; ------------------------------------------------------
    ; Load BG1 tile data into VRAM $0000 via DMA (channel 2)
    ; ------------------------------------------------------

    ; VRAM address = $0000 -> word addr 0
    STZ $2116
    STZ $2117

    ; DMAP2: mode 1, write to $2118/9
    LDA #$01
    STA $4320
    LDA #$18
    STA $4321

    LDA #<TilesFrame0
    STA $4322
    LDA #>TilesFrame0
    STA $4323
    LDA #^TilesFrame0
    STA $4324

    ; Size: 57344 bytes = 0xE000
    LDA #$00
    STA $4327           ; high size
    LDA #<$E000
    STA $4325
    LDA #>$E000
    STA $4326

    LDA #$04
    STA $420B           ; start DMA ch2

    ; ------------------------------------------------------
    ; Turn screen on, mid brightness
    ; ------------------------------------------------------

    LDA #$0F            ; brightness 15, no forced blank
    STA $2100

Forever:
    BRA Forever         ; loop forever

    ; ------------------------------------------------------
    ; Internal header & vectors (LoROM)
    ; ------------------------------------------------------

    .ORG $FFC0
    ; 21-byte title
    .DB "MODE3 DEMO SNES     "
    ; Map / ROM info
    .DB $00     ; ROM makeup (LoROM)
    .DB $00     ; ROM type
    .DB $08     ; ROM size (2 banks = 128KB => 2^8KB = $08)
    .DB $00     ; SRAM size (none)
    .DB $00     ; Country
    .DB $00     ; License
    .DB $00     ; Version
    .DW $0000   ; complement
    .DW $0000   ; checksum

    ; Native & emulation vectors (we just set emulation ones)
    .ORG $FFEA
    .DW 0       ; NMI
    .DW 0       ; RESET (native)
    .DW 0       ; IRQ/BRK (native)

    .ORG $FFFA
    .DW 0       ; NMI (emulation)
    .DW Start   ; RESET (emulation)
    .DW 0       ; IRQ/BRK (emulation)


    ; ----------------------------------------------------------
    ; Bank 1 - data (palette, tilemap, tiles)
    ; ----------------------------------------------------------

    .BANK 1 SLOT 0
    .ORG $8000

PaletteData:
    .INCBIN "palette/mode3_bg1_palette.pal"

TilemapData:
    .INCBIN "tilemap/mode3_bg1_tilemap.bin"

TilesFrame0:
    .INCBIN "tiles/frame_001_tiles.bin"
